language: cpp
compiler: gcc
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    packages:
      - gcc-5
      - g++-5
before_script:
  - ls
  - sudo apt-get update -qq
  - sudo apt-get install libboost-system-dev
  - wget https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz
  - tar xvfz protobuf-cpp-3.0.0.tar.gz
  - ( cd protobuf-3.0.0 && ./configure --prefix=$HOME/protobuf-3.0.0-bin && make -j2 && make install )
  - PATH=$PATH:$HOME/protobuf-3.0.0-bin/bin
script:
- cd build
- cmake ../ && make
- cd ..
