language: cpp
compiler: gcc
cache:
  directories:
  - $HOME/protobuf-3.0.0-bin/
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - gem install coveralls-lcov

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libboost-system-dev
      - lcov

before_script:
  - (cd build && bash installProtobuf.sh && cd ..)
  - PATH=$PATH:$HOME/protobuf-3.0.0-bin/bin
  - PROTOC_PATH=$HOME/protobuf-3.0.0-bin/
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xzf release-1.8.0.tar.gz
  - ln -s googletest-release-1.8.0/googletest googletest
  - ln -s googletest-release-1.8.0/googlemock googlemock
  - (cd build && lcov --directory . --zerocounters && cd ..)

script:
- ( cd build && cmake ../ -DPROTOC_PATH=$PROTOC_PATH && make -j && make runTests && cd .. )

after_success:
- (cd build && bash generateAndSubmitCoverallsReport.sh && cd ..)
