language: cpp
compiler: gcc
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-system-dev
  - wget https://github.com/google/protobuf/releases/download/v3.0.0/protobuf-cpp-3.0.0.tar.gz
  - tar xvfz protobuf-cpp-3.0.0.tar.gz
  - cd protobuf-cpp-3.0.0
  - ./configure && make install
script:
- cd build
- cmake ../ && make
- cd ..
