language: cpp
compiler: gcc
cache:
  directories:
  - $HOME/protobuf-3.0.0-bin/
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
      - libboost-system-dev
before_script:
  - pwd
  - ls -la
  - ls -la ..
  - ls -la ../..
  - ls -la ../../..
  - (cd build && bash installProtobuf.sh && cd ..)
  - ls -la
  - PATH=$PATH:$HOME/protobuf-3.0.0-bin/bin
  - PROTOC_PATH=$HOME/protobuf-3.0.0-bin/
  - wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
  - tar xzf release-1.8.0.tar.gz
  - ln -s googletest-release-1.8.0/googletest googletest
  - ln -s googletest-release-1.8.0/googlemock googlemock
script:
- ( cd build && cmake ../ -DPROTOC_PATH=$PROTOC_PATH && make && make runTests && cd .. )
